In [1]:
import numpy as np

# List vs Numpy

In [2]:
List = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
Numpy = np.array(List)

## add 1 on each element

In [4]:
# List
addedList = []
for i in List:
    tmp = []
    for j in i:
        tmp.append(j + 1)
    addedList.append(tmp)
print(addedList)

# numpy
print(Numpy + 1)

[[12, 13, 14], [22, 23, 24], [32, 33, 34]]
[[12 13 14]
 [22 23 24]
 [32 33 34]]


easier to write   
there are a lot of functions to use easily

In [11]:
print(np.sum(Numpy))
print(np.mean(Numpy))
print(np.average(Numpy, axis=1, weights=[1. / 3, 2. / 6, 3. / 8]))

198
22.0
[12.04 22.04 32.04]


## execution time

In [16]:
rows = 10000
cols = 10000

randomArray = np.random.rand(rows, cols)
randomList = randomArray.tolist()

In [17]:
import time
#모든 원소에 +1
start = time.time()
randomList2 = []
for list in randomList:
    tempList = []
    for e in list:
        tempList.append(e + 1)
    randomList2.append(tempList)
print(time.time() - start)

print("------------")

start = time.time()
addedArray = randomArray + 1
print(time.time() - start)

13.017381429672241
------------
0.8581597805023193


---

# 다차원 배열 만들기
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

## numpy.empty
- 초기화없이, given shape, type에 맞추어 array 생성

In [3]:
np.empty((2, 3), dtype='int')

array([[          0,           0,  -867275824],
       [        294,           0, -2147483648]])

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 3x3 array

In [10]:
# A와 같은 shape의 array 생성 ( 초기화 X )
np.empty_like(A)

array([[1, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

## numpy.zeros
- empty와 같으나 0으로 초기화

In [12]:
# default type = float
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2, 3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## numpy.ones
- 1로 초기화

In [15]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones((2, 3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## numpy.identity
- 단위행렬

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.identity(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 참고

### np.eye

In [20]:
# diagonal entry = 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
np.eye(3, 4, 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(3, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### np.full

In [25]:
# fill value with given
np.full((3, 4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [26]:
# commonly used like..
10 * np.ones((3, 4), dtype='int')

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

### np.arange

In [29]:
# return evenly spaced values
np.arange(10)

# default parameter : start = 0, step = 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(start=0, stop=10, step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### np.linspace

In [31]:
# return evenly spaced values over specified value
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Practice

- 2*2 integers 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [34]:
np.empty((2, 2), dtype='int')

array([[         0, 1072693248],
       [         0, 1072693248]])

- X = np.array([1,2,3], [4,5,6], np.int32) 일 때,
X와 동일한 shape를 가지는 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [33]:
X = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

np.empty_like(X)

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

- 크기가 3인 단위행렬을 생성하세요.

In [35]:
np.identity(3)  # or np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- 모든 원소가 1로 채워진 3*2 실수형 다차원 배열을 생성하세요.

In [37]:
np.ones((3, 2), dtype='float')

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- x = np.arange(4, dtype=np.int64) 일 때, x와 동일한 shape의 영행렬을 생성하세요.

In [38]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

- 모든 원소가 6으로 채워진 2*5 uint형(부호없는 정수) 다차원 배열을 생성하세요.

In [39]:
6 * np.ones((2, 5), dtype='uint')

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

- x = np.arange(4, dtype=np.int64)일 때, x와 동일한 shape이고 모든 원소가 6인 다차원 배열을 생성하세요.

In [40]:
x = np.arange(4, dtype=np.int64)
6 * np.ones_like(x)

array([6, 6, 6, 6], dtype=int64)

- [1, 2, 3] 배열을 생성하세요

In [41]:
np.array([1, 2, 3])

array([1, 2, 3])

- x = [1, 2] 일 때(python list 상태) x를 배열로 변환하세요.

In [42]:
x = [1, 2]
np.array(x)

array([1, 2])

- x = [1, 2] 일 때(python list 상태) x를 `float`형 배열로 변환하세요.

In [46]:
np.array(x, dtype=float)
# or np.asfarray(x)

array([1., 2.])

- 2, 4, 6, 8, ..., 100 을 원소로 가지는 배열을 생성하세요.

In [48]:
np.arange(start=2, stop=101, step=2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

- 3.0 에서 10.0 까지 50개의 원소가 균일하게 분포된 1차원 배열을 생성하세요.

In [45]:
np.linspace(start=3, stop=10, num=50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])