In [1]:
import numpy as np

# 다차원 배열 다루기

![alt text](https://lh3.googleusercontent.com/zXC7mbgObMUkQoUnkfMvog5wU8Qh2bvLEwINZo7eilDpq_aun8c3D_qCvaCZhQQLnC-iz7XxFP3iWylf3RZWNsKUaw2MFU0c4Oiu3cbZIPM4AsgSSUVYlDzZKVgG-ldbaEt2vty-cqaHNqrIYNPjsN6n8gT5XbJPqEk5GJjjTfL61t5ugfaDtHjbskwoZm45x8xbWJgkilc8fZ70hWGr8tpskk_5P4G3dI9zy0-ZNTDF9R2nGknAjcmCT3cP5nKhL0YM8mhhbWxS7jTotR1A-hKBPRXbu-5tFa1W54F8k4Do17Wvhz_JNaj0EX-5z0BT8ryE6XPvsJd4vlQAAzwYKdy9oIL7KYzTiIy3vi7MicCg7opIc87ueczPBpZUv2vczrUzzOT-6Yczc9Ay2UPvzyS6SmB2QJI2gGXXvdRFZAElecn83X98psuIHAGx7xii7OplLOQLNaDN3o0tCt4v0e2mgnP8zU87MfUGMCgs-zJwCZYeJz-2rt1EHGGk0IuiiDJQ-R_X91KUE1Z76VOHOjBt_saj-UJ40dTB2w_ITArQa1dH2GhPZCz7wC4_UmwYlr1BHUiohA1ByDBHRB2cA8sBF5MU3s7F1KKWPQUcBQqf2NhQgUJTYWnvWUrgqdmvEKRVRiXwqlJiwGVc1_nCFUAOtzXqLtJAvT0mlKso-GUEPy6NPFjR-Yvv4ci_QFfhtUh87MyVYTEphY7xcNwTaswPqw=w652-h341-no)

## numpy.amin
- return minimum

In [12]:
A = np.array([[1,50,3],[4,5,6],[7,8,9]])
A

array([[ 1, 50,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [13]:
np.amin(A, axis = 0)

array([1, 5, 3])

In [14]:
np.amin(A, axis = 1)

array([1, 4, 7])

In [15]:
np.amin(A)

1

## np.amax
- return maximum

In [19]:
A

array([[ 1, 50,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
np.amax(A, 0)

array([ 7, 50,  9])

In [17]:
np.amax(A,1)

array([50,  6,  9])

In [18]:
np.amax(A)

50

## np.ptp
- peak to peak
- range of values between max & min

In [20]:
A

array([[ 1, 50,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
np.ptp(A, 0)

array([ 6, 45,  6])

In [22]:
np.ptp(A,1)

array([49,  2,  2])

In [23]:
np.ptp(A)

49

## np.median
- return median value

In [24]:
A

array([[ 1, 50,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [25]:
np.median(A,0)

array([4., 8., 6.])

In [26]:
np.median(A,1)

array([3., 5., 8.])

In [27]:
np.median(A)

6.0

## np.mean
- return mean value

In [28]:
A

array([[ 1, 50,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
np.mean(A,0)

array([ 4., 21.,  6.])

In [30]:
np.mean(A,1)

array([18.,  5.,  8.])

In [31]:
np.mean(A)

10.333333333333334

## np.var
- return variance

In [32]:
np.var(A,0)

array([  6., 422.,   6.])

In [33]:
np.var(A,1)

array([512.66666667,   0.66666667,   0.66666667])

In [34]:
np.var(A)

202.22222222222223

## np.std
- standard deviation

In [35]:
np.std(A,0)

array([ 2.44948974, 20.54263858,  2.44948974])

In [36]:
np.std(A,1)

array([22.6421436 ,  0.81649658,  0.81649658])

In [37]:
np.std(A)

14.220486005134362

## Slicing
`a[ : , : ]`   
`a[행 슬라이싱 시작:행 슬라이싱 끝, 열 슬라이싱 시작:열 슬라이싱 끝]`

In [39]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
a[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

## Indexing

In [46]:
# this way is more commonly used
a[0, 0]

1

In [47]:
a[0][0]

1

In [49]:
# take all rows, and only 0,1,3 columns
a[:, [0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

## Indexing & Slicing - dimension

In [50]:
print(a, a.shape, a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


In [54]:
slicedRow = a[0:1, :]
print(slicedRow, slicedRow.shape, slicedRow.ndim)
# still 2 dim

[[1 2 3 4]] (1, 4) 2


In [57]:
indexedRow = a[0] # take first row
print(indexedRow, indexedRow.shape, indexedRow.ndim)

indexedRow2 = a[0,:]
print(indexedRow2,indexedRow2.shape, indexedRow2.ndim)
# 1 dim

[1 2 3 4] (4,) 1
[1 2 3 4] (4,) 1


In [65]:
slicedCol = a[:, :1]
print(slicedCol, slicedCol.shape, slicedCol.ndim)
# 2 dim

[[1]
 [5]
 [9]] (3, 1) 2


In [66]:
indexedCol = a[:, 0]
print(indexedCol, indexedCol.shape, indexedCol.ndim)
# 1 dim

[1 5 9] (3,) 1


Slicing method is recommended due to <font color="red">dimension issue</font>

## Indexing&Slicing - copy&reference

In [67]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
# indexing value
b = a[0,0]

b = 100

print(a[0,0])

1


- Indexing copies original value, so does not change original value

In [72]:
# slicing value
c = a[:1,:1] # a[0,0]
c[0,0] = 100
print(a[0,0])

100


- <font color="red">Slicing</font> refers to original value, <font color="red">so the original value changes</font>

## Boolean Array Indexing
- Filtering!

In [73]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
bool_idx = ( a > 2)
# return True if value is larger than 2
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [76]:
# Index which is True
a[bool_idx]

array([3, 4, 5, 6])

In [77]:
# i.e.
a[a>2]

array([3, 4, 5, 6])

## Integer Array Indexing

In [78]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
# a [0,0] = 1 [1,1] = 4 [2,0] = 5
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [81]:
# equals
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [82]:
# can reuse same element
a[[0,0],[1,1]] # (0,1), (0,1)

array([2, 2])

## Transpose

In [85]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [87]:
# 1dim array does not change 
v = np.array([1,2,3])
print(v, v.T)

[1 2 3] [1 2 3]


# Shape 변경

## np.reshape

In [88]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [89]:
np.arange(6).reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [91]:
a = np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [93]:
np.reshape(a, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
# 2 dimension
np.reshape(a, (1,6))

array([[0, 1, 2, 3, 4, 5]])

In [96]:
# 1 dimension
np.reshape(a, 6)

array([0, 1, 2, 3, 4, 5])

## np.ravel
- flatten array

In [99]:
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [103]:
# 2dim --> 1dim
print(np.ravel(a))
print(a.ravel())

[0 1 2 3 4 5]
[0 1 2 3 4 5]


## np.ndarray.flatten

In [105]:
# can be used like this
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [106]:
# cant use like this
np.flatten(a)

AttributeError: module 'numpy' has no attribute 'flatten'

### ravel vs flatten

1. flatten --> used by only method
2. ravel --> 뷰 반환   
   flatten --> 복사본 반환   

In [111]:
# ravel method refers to original value, so it changes the value
a = np.array([[1,2,3],[4,5,6]])
raveled = a.ravel()
raveled[0] = 100
print(a)

[[100   2   3]
 [  4   5   6]]


In [112]:
# flatten method does not change original value, cause if makes duplicate
a = np.array([[1,2,3],[4,5,6]])
flattened = a.flatten()
flattened[0] = 100
print(a)

[[1 2 3]
 [4 5 6]]


## np.concatenate

In [113]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [114]:
np.concatenate( (a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [120]:
print(b)
print(b.shape)
print(b.T.shape)

[[5 6]]
(1, 2)
(2, 1)


In [117]:
np.concatenate( (a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

# Reference
- https://docs.scipy.org/doc/numpy/reference/routines.math.html

# Practice

Q1. x가 10x10x3의 다차원 배열일때, x의 두번째 차원이 150인 2차원 배열이 되도록 reshape하세요.

In [125]:
x = np.ones((10,10,3))
x = x.reshape(2,150)
print(x.shape)

(2, 150)


Q2. x가 [[1, 2, 3], [4, 5, 6]]일 때, [1 2 3 4 5 6]로 변환하세요.

In [126]:
x = np.array([[1,2,3],[4,5,6]])
x = x.flatten()
print(x)

[1 2 3 4 5 6]


Q3. x가 [[1, 2, 3], [4, 5, 6]]일 때, flatten한 후 5번째 원소를 가져오세요.

In [127]:
x = np.array([[1,2,3],[4,5,6]])
x = x.flatten()
print(x[4])

5


Q4. 

x= <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
y = <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>


x와 y를 연결해서
<br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]]
를 만드세요


In [129]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate((x,y), axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q5. 

x= <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
y = <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>


x와 y를 연결해서
<br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]
를 만드세요

In [130]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate((x,y), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q6. x가 [0, 1, 2]일 때, [0, 0, 1, 1, 2, 2]를 생성하세요.

In [132]:
x = np.array([0,1,2])
np.repeat(x, 2)

array([0, 0, 1, 1, 2, 2])

In [134]:
x[[0,0,1,1,2,2]]

array([0, 0, 1, 1, 2, 2])

Q7. x가 [0, 0, 0, 1, 2, 3, 0, 2, 1, 0]일 때,<br/>
앞, 뒤의 0을 제거하세요.

In [138]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
x[3:-1]

array([1, 2, 3, 0, 2, 1])

In [136]:
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])