In [1]:
import numpy as np

# 다차원 배열 연산
- 기본적 수학함수는 배열의 각 요소별로 동작
- 연산자 or np 함수 모듈을 통해 동작
- 다차원 배열 간 연산은 shape이 맞아야 동작

In [8]:
x = np.array([[1., 2.], [3., 4.]])
y = np.array([[5., 6.], [7., 8.]])
v = np.array([9,10])
w = np.array([11, 12])

## 사칙연산

In [3]:
# add
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [4]:
# sub
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [5]:
# mul
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [6]:
# div
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [7]:
# sqrt
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


## 내적
- x, y : matrix(2,2)
- v, w : vector(2,)

In [19]:
# 벡터의 내적 : scalar
print(v.dot(w))
print(np.dot(v, w))

219
219


In [16]:
# 행렬과 벡터의 곱 : 2x1 vector
print(x.dot(v))
print(np.dot(x, v))

[29. 67.]
[29. 67.]


In [18]:
# 행렬간 곱 : 2x2 matrix
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


# 브로드캐스팅(Broadcasting)

In [28]:
# x : 4x3 matrix
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
# v : 3, vector
v = np.array([1, 0, 1])
print('x = \n',x)
print("------------")
print('v = \n', v)

x = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------
v = 
 [1 0 1]


In [30]:
y = np.empty_like(x)
for i in range(4):
    y[i,:] = x[i,:] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [34]:
# Broadcasting
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

- Broadcasting   
    : 각 배열 shape의 요소별 최소 공배수로 이루어진 shape이 두 배열의 shape으로 간주하여 계산   
    : 두 배열의 shape이 최소공배수가 존재하지 않는다면 불가능할 것!


In [35]:
v = np.array([1,2,3])  # v shape (3,)
w = np.array([4,5])    # w shape (2,)
x = np.array([[1,2,3], 
              [4,5,6]])

In [36]:
# (2,3), (3,) --> 가능
x+v

array([[2, 4, 6],
       [5, 7, 9]])

In [37]:
# (2,3), (2,) --> 불가능
x+w

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [39]:
# x.T shape : (3,2) + (2,) --> 가능
x.T + w

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [42]:
# 이를 다시 Transpose하면 x에 열벡터 w 덧셈 가능
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [43]:
# w shape을 (2,1)로 reshape
x + w.reshape(2,1)

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [44]:
# 행렬에 스칼라곱도 가능
x * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])